"""Harness hooks: one `orchestra hook` binary, one OpenCode plugin (DESIGN §6).

Hooks are mandatory and install at `orchestra init`. Claude, Codex and
Reasonix all run a command hook and hand it the event as JSON on stdin, so
ONE subcommand serves all three; only the file each one is registered in,
and the JSON shape of that file, differ.

Verified against the installed CLIs (2026-08-13, research/hook-matrix):

- Claude Code  ``$CLAUDE_CONFIG_DIR/settings.json`` (default ``~/.claude``),
  ``hooks.<Event>`` is a list of MATCHER GROUPS: ``[{"hooks": [handler]}]``.
- Codex        ``$CODEX_HOME/hooks.json`` (default ``~/.codex``), same
  matcher-group shape. Enabled hooks additionally need persisted TRUST.
- Reasonix     ``$REASONIX_HOME/settings.json`` (default ``~/.reasonix``),
  ``hooks.<Event>`` is a FLAT list of handlers. The matcher-group shape
  reports ``status: invalid`` in `reasonix hook list --json`; the flat one
  reports ``active``. The hook-matrix calls Reasonix "Claude-compatible",
  which is true of the event names and the wire protocol but NOT of this
  nesting.
- OpenCode     no shell hooks at all. It gets a JS plugin listening for
  ``session.idle`` and ``permission.asked``, delivered per run through
  ``OPENCODE_CONFIG_CONTENT`` so only Orchestra's own runs load it.

The hook does nothing at all unless ``ORCHESTRA_RUN_ID`` is set. It is
installed user-wide, so it fires inside the human's own interactive
sessions too, and it must never interfere with one.
"""
import hashlib
import json
import os
import re

from orchestra import config, db, messaging, paths, traces

# A Stop hook that holds a session open for an `ask` needs a timeout longer
# than the human takes to answer. Same figure Orchestra ran in production.
HOOK_TIMEOUT = 36_000
BIND_TIMEOUT = 10
STATUS_MESSAGE = "Waiting for Orchestra"
NESTED_BACKENDS = ("claude", "codex")   # matcher-group shape
SESSION_RE = re.compile(r"^[A-Za-z0-9._:-]{1,256}$")


def command(backend: str, bind: bool = False) -> str:
    return f"orchestra hook --backend {backend}" + (" --bind" if bind else "")


def handler(backend: str, bind: bool = False) -> dict:
    entry = {"type": "command", "command": command(backend, bind),
             "timeout": BIND_TIMEOUT if bind else HOOK_TIMEOUT}
    if not bind:
        entry["statusMessage"] = STATUS_MESSAGE
    return entry


def _entry(backend: str, bind: bool = False) -> dict:
    """One installable unit, in the shape that backend's file wants."""
    if backend in NESTED_BACKENDS:
        return {"hooks": [handler(backend, bind)]}
    return handler(backend, bind)


def _handlers(group) -> list:
    """The command handlers inside one installed unit, either shape."""
    if isinstance(group, dict) and isinstance(group.get("hooks"), list):
        return [h for h in group["hooks"] if isinstance(h, dict)]
    return [group] if isinstance(group, dict) else []


# --- installing --------------------------------------------------------------

def install_file(path, backend: str) -> str:
    """Merge Orchestra's Stop and SessionStart hooks into a harness config file.

    Idempotent and additive: an existing file is read, our entries are matched
    by their command string, and everything else in it is left alone. The
    human's own hooks live in these files too.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8") or "{}")
        except (OSError, UnicodeError, ValueError) as exc:
            raise RuntimeError(f"cannot merge orchestra hooks into {path}: {exc}") from exc
        if not isinstance(data, dict):
            raise RuntimeError(f"cannot merge orchestra hooks into {path}: "
                               "the root must be a JSON object")
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise RuntimeError(f"cannot merge orchestra hooks into {path}: "
                           "\"hooks\" must be a JSON object")
    added = []
    for event, bind in (("SessionStart", True), ("Stop", False)):
        groups = hooks.setdefault(event, [])
        if not isinstance(groups, list):
            raise RuntimeError(f"cannot merge orchestra hooks into {path}: "
                               f"hooks.{event} must be a list")
        wanted = command(backend, bind)
        if any(h.get("command") == wanted for g in groups for h in _handlers(g)):
            continue
        groups.append(_entry(backend, bind))
        added.append(event)
    if added:
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return f"{path} ({', '.join(added) + ' installed' if added else 'already present'})"


OPENCODE_PLUGIN = """\
// Generated by `orchestra init` (DESIGN §6). Safe for Orchestra to replace.
// OpenCode has no shell hooks, so this plugin is the equivalent: it wakes
// Orchestra when a session goes idle or blocks on a permission, and injects
// whatever Orchestra answers back into the same session.
export const OrchestraPlugin = async ({ client, $, directory }) => {
  const busy = new Set()
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle" && event.type !== "permission.asked") return
      const sessionID = event.properties?.sessionID
      if (!sessionID || busy.has(sessionID)) return
      busy.add(sessionID)
      try {
        const out = await $`orchestra hook --backend opencode --event ${event.type} --session ${sessionID}`.nothrow().text()
        const text = (out || "").trim()
        if (!text || event.type !== "session.idle") return
        await client.session.promptAsync({
          path: { id: sessionID },
          query: { directory },
          body: { parts: [{ type: "text", text }] },
        })
      } finally {
        busy.delete(sessionID)
      }
    },
  }
}

export default OrchestraPlugin
"""


def install_opencode_plugin() -> str:
    path = paths.opencode_plugin_path()
    if path.exists() and path.read_text(encoding="utf-8") == OPENCODE_PLUGIN:
        return f"{path} (already present)"
    path.write_text(OPENCODE_PLUGIN, encoding="utf-8")
    return f"{path} (written)"


def install_all() -> list[str]:
    """Everything `orchestra init` puts in place. Returns one line per backend."""
    return [
        "claude:   " + install_file(paths.claude_settings_path(), "claude"),
        "codex:    " + install_file(paths.codex_home() / "hooks.json", "codex"),
        "          " + provision_codex_trust(),
        "reasonix: " + install_file(paths.reasonix_settings_path(), "reasonix"),
        "opencode: " + install_opencode_plugin(),
    ]


# --- Codex hook trust ---------------------------------------------------------
# Codex will not run a non-managed hook until that exact hook definition has
# been trusted once. The trust record lives in $CODEX_HOME/config.toml as
#   [hooks.state."<hooks.json path>:<event lowercase>:<group>:<index>"]
#   enabled = true
#   trusted_hash = "sha256:<hex>"
# Spawning with --dangerously-bypass-hook-trust would make every run skip that
# check, which silently disables a deliberate safety feature. So Orchestra
# provisions the record once, at init, and `orchestra doctor` reports it. The
# flag stays a documented escape hatch, never the default.

def codex_trust_key(hooks_path, event: str, group: int = 0, index: int = 0) -> str:
    return f"{hooks_path}:{event.lower()}:{group}:{index}"


def codex_trust_hash(entry: dict) -> str:
    """The hash Codex stores next to a trusted hook.

    ponytail: the preimage is our best reading of Codex's HookStateToml —
    the handler object as canonical compact JSON. If Codex disagrees it
    reports the hook as "New hook - review required" in `/hooks` and simply
    does not run it (fails CLOSED, never open), and trusting it once there
    overwrites this record with the right one. Orchestra never overwrites a
    record it did not write.
    """
    canonical = json.dumps(entry, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()


def codex_trust_records() -> list[tuple[str, str]]:
    """(key, trusted_hash) for each hook Orchestra installs for Codex."""
    # Resolved: Codex keys the record on the path IT resolved the file to.
    hooks_path = (paths.codex_home() / "hooks.json").resolve()
    try:
        data = json.loads(hooks_path.read_text(encoding="utf-8"))
        events = data["hooks"]
    except (OSError, UnicodeError, ValueError, KeyError, TypeError):
        return []
    out = []
    for event, bind in (("SessionStart", True), ("Stop", False)):
        wanted = command("codex", bind)
        for gi, group in enumerate(events.get(event) or []):
            for hi, item in enumerate(_handlers(group)):
                if item.get("command") == wanted:
                    out.append((codex_trust_key(hooks_path, event, gi, hi),
                                codex_trust_hash(item)))
    return out


def codex_trust_status() -> str:
    """What `orchestra doctor` prints: is every installed Codex hook trusted?"""
    records = codex_trust_records()
    if not records:
        return "no orchestra hook installed in " + str(paths.codex_home() / "hooks.json")
    path = paths.codex_home() / "config.toml"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return f"NOT provisioned ({path} unreadable) — run `orchestra init`"
    missing = [key for key, _ in records
               if _trust_header(key) not in text
               and f'[hooks.state."{key}"]' not in text]
    if missing:
        return (f"NOT provisioned for {len(missing)} of {len(records)} hooks — "
                "run `orchestra init`")
    return f"provisioned for {len(records)} hook(s) in {path}"


def _toml_basic(value: str) -> str:
    """Escape a value for a TOML basic string. Windows paths need this:
    ``C:\\Users\\...`` otherwise ``\\U`` is a unicode escape and Codex
    refuses the whole config.toml."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _trust_header(key: str) -> str:
    return f'[hooks.state."{_toml_basic(key)}"]'


def provision_codex_trust() -> str:
    """Write the trust records Codex needs, without touching existing ones.

    Appends whole TOML tables to the end of config.toml: a table header ends
    the previous table, so appending is unambiguous, and stdlib has no TOML
    writer to do anything cleverer with.
    """
    records = codex_trust_records()
    if not records:
        return "hook trust: nothing to trust (no codex hook installed)"
    path = paths.codex_home() / "config.toml"
    try:
        text = path.read_text(encoding="utf-8") if path.exists() else ""
    except (OSError, UnicodeError) as exc:
        return f"hook trust: cannot read {path}: {exc}"
    lines = []
    for key, digest in records:
        if _trust_header(key) in text or f'[hooks.state."{key}"]' in text:
            continue  # already recorded — possibly by Codex itself; leave it
        lines += [_trust_header(key), "enabled = true",
                  f'trusted_hash = "{digest}"', ""]
    if not lines:
        return f"hook trust: already recorded in {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(("\n" if text and not text.endswith("\n") else "")
                     + "\n".join(lines) + "\n")
    return (f"hook trust: recorded {len(lines) // 4} hook(s) in {path} "
            "(if Codex still asks, approve once with /hooks)")


# --- the hook itself ----------------------------------------------------------

def valid_session(value) -> str | None:
    """Only bounded, shell-safe session identifiers, from any harness."""
    return value if isinstance(value, str) and SESSION_RE.fullmatch(value) else None


def _is_start(event: str, payload: dict) -> bool:
    name = (event or payload.get("hook_event_name") or "").lower()
    return name.startswith("sessionstart") or name == "session.start"


def render(backend: str, text: str | None) -> str:
    """The hook's answer, in the shape the harness reads.

    OpenCode's plugin takes plain text off stdout. Claude, Codex and Reasonix
    read a JSON object: ``decision: block`` with a reason is what keeps a
    stopping session alive and feeds the reason back as its next input.
    """
    if backend == "opencode":
        return text or ""
    return json.dumps({"decision": "block", "reason": text}) if text else "{}"


def run_hook(backend: str, payload: dict, *, bind: bool = False,
             event: str | None = None, session: str | None = None) -> str | None:
    """Handle one lifecycle event. Returns text to inject, or None.

    Silent and side-effect-free outside a Orchestra run: this hook is installed
    user-wide and fires in the human's own sessions too.
    """
    try:
        run_id = int(paths.env("ORCHESTRA_RUN_ID"))
    except (KeyError, ValueError):
        return None
    session_id = valid_session(session) or valid_session(payload.get("session_id")) \
        or valid_session(payload.get("sessionID")) or valid_session(payload.get("sessionId"))
    con = db.connect()
    try:
        run = con.execute("SELECT * FROM runs WHERE id=?", (run_id,)).fetchone()
        if run is None:
            return None
        if session_id and not run["session_ref"]:
            # Only Claude lets Orchestra pre-assign an id; everywhere else this
            # is the earliest honest moment to learn it, and `tell` needs it.
            con.execute("UPDATE runs SET session_ref=? WHERE id=? AND session_ref IS NULL",
                        (session_id, run_id))
            con.commit()
        if bind or _is_start(event or "", payload):
            return None
        if event == "permission.asked":
            # OpenCode's only "the run is stuck" signal. Recording it makes a
            # blocked run visible in the trace; nothing is injected.
            traces.record_lifecycle(con, run_id, "permission.asked",
                                    json.dumps(payload)[:2000])
            return None
        if run["status"] in db.RUN_TERMINAL:
            return None  # killed under us; do not resurrect the session
        cfg = config.load(run["project_id"])
        parts = []
        pending_ask = messaging.open_ask(con, run_id)
        if pending_ask is not None:
            parts.append(messaging.await_answer(con, cfg, pending_ask))
        delivered = messaging.claim_pending(con, run_id)
        if delivered:
            parts.append(messaging.render_delivery(delivered))
        if not parts:
            return None
        parts.append("Then continue the original mission and end with the usual "
                     "handoff summary.")
        return "\n\n".join(parts)
    finally:
        con.close()


def hook_report() -> list[str]:
    """`orchestra doctor`: is each backend actually wired up?"""
    lines = []
    for backend, path in (("claude", paths.claude_settings_path()),
                          ("codex", paths.codex_home() / "hooks.json"),
                          ("reasonix", paths.reasonix_settings_path())):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            events = data.get("hooks") or {}
        except (OSError, UnicodeError, ValueError, AttributeError):
            events = {}
        found = [event for event, bind in (("SessionStart", True), ("Stop", False))
                 if any(h.get("command") == command(backend, bind)
                        for g in (events.get(event) or []) for h in _handlers(g))]
        lines.append(f"  hooks {backend:<9} "
                     + (", ".join(found) + f" in {path}" if found
                        else f"NOT installed ({path}) — run `orchestra init`"))
    plugin = paths.opencode_plugin_path()
    lines.append(f"  hooks opencode  "
                 + (f"plugin {plugin}" if plugin.exists()
                    else f"NOT installed ({plugin}) — run `orchestra init`"))
    lines.append(f"  codex trust     {codex_trust_status()}")
    return lines
