// Generated by `orchestra init`. Keeps an idle harness attached to its runs.
export const OrchestraPlugin = async ({ client, $, directory }) => {
  const waiting = new Set()
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return
      const sessionID = event.properties.sessionID
      if (waiting.has(sessionID)) return
      waiting.add(sessionID)
      try {
        const prompt = (await $`orchestra hook --backend opencode`.nothrow().text()).trim()
        if (!prompt) return
        await client.session.promptAsync({
          path: { id: sessionID },
          query: { directory },
          body: { parts: [{ type: "text", text: prompt }] },
        })
      } finally {
        waiting.delete(sessionID)
      }
    },
  }
}

export default OrchestraPlugin
