"""Wake interactive harnesses when their Orchestra work needs attention."""
from __future__ import annotations

import json
import os
import time
from pathlib import Path

from orchestra_cli import config, db, reap


_RUN_DELIVERY_KINDS = ("interrupt", "checkin", "queued")
_HOOK_TIMEOUT_SECONDS = 36000

_CODEX_HANDLER = {
    "type": "command",
    "command": "orchestra hook --backend codex",
    "timeout": _HOOK_TIMEOUT_SECONDS,
    "statusMessage": "Waiting for Orchestra workers",
}
_CLAUDE_HANDLER = {
    "type": "command",
    "command": "orchestra hook --backend claude",
    "timeout": _HOOK_TIMEOUT_SECONDS,
    "statusMessage": "Waiting for Orchestra workers",
}

_OPENCODE_PLUGIN = """\
// Generated by `orchestra init`. Keeps an idle harness attached to its runs.
export const OrchestraPlugin = async ({ client, $, directory }) => {
  const waiting = new Set()
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return
      const sessionID = event.properties.sessionID
      if (waiting.has(sessionID)) return
      waiting.add(sessionID)
      try {
        const prompt = (await $`orchestra hook --backend opencode`.nothrow().text()).trim()
        if (!prompt) return
        await client.session.promptAsync({
          path: { id: sessionID },
          query: { directory },
          body: { parts: [{ type: "text", text: prompt }] },
        })
      } finally {
        waiting.delete(sessionID)
      }
    },
  }
}

export default OrchestraPlugin
"""


def _active_owned_runs(con, recipient: str, current_run_id: int | None) -> list[int]:
    query = (
        "SELECT id FROM runs WHERE requested_by=? "
        "AND status NOT IN ('done','failed','timeout','killed')"
    )
    params: list[object] = [recipient]
    if current_run_id is not None:
        query += " AND id != ?"
        params.append(current_run_id)
    return [int(row["id"]) for row in con.execute(query + " ORDER BY id", params)]


def _claim_messages(con, recipient: str):
    """Claim harness mail without stealing supervisor-owned runner delivery."""
    placeholders = ",".join("?" for _ in _RUN_DELIVERY_KINDS)
    query = (
        "SELECT * FROM messages WHERE recipient=? AND read_at IS NULL "
        "AND recalled_at IS NULL "
        f"AND COALESCE(kind,'') NOT IN ({placeholders}) ORDER BY id LIMIT 20"
    )
    params = (recipient, *_RUN_DELIVERY_KINDS)
    con.execute("BEGIN IMMEDIATE")
    rows = list(con.execute(query, params))
    if rows:
        ids = ",".join(str(int(row["id"])) for row in rows)
        con.execute(
            f"UPDATE messages SET read_at=? WHERE id IN ({ids}) AND read_at IS NULL",
            (db.now(),),
        )
    con.execute("COMMIT")
    return rows


def wait_for_attention(root: Path, *, poll_interval: float = 0.25) -> str | None:
    """Wait while this harness owns live runs, returning the next durable event."""
    cfg = config.load(root)
    recipient = os.environ.get("ORCHESTRA_SELF") or cfg["settings"].get(
        "default_requester", "orchestrator"
    )
    try:
        current_run_id = int(os.environ["ORCHESTRA_RUN_ID"])
    except (KeyError, ValueError):
        current_run_id = None

    con = db.connect(root)
    try:
        next_reap_at = 0.0
        while True:
            now = time.monotonic()
            if now >= next_reap_at:
                reap.reap_orphans(con, root)
                next_reap_at = now + 5
            messages = _claim_messages(con, recipient)
            if messages:
                rendered = "\n\n".join(
                    f"[message {row['id']} from {row['sender']}]\n{row['body']}"
                    for row in messages
                )
                return (
                    "Orchestra received the following event(s) while you were waiting. "
                    "Handle them now: answer blocking questions, send guidance for "
                    "consultations, and verify completed work before accepting it.\n\n"
                    f"{rendered}"
                )
            if not _active_owned_runs(con, recipient, current_run_id):
                return None
            time.sleep(poll_interval)
    finally:
        con.close()


def render_hook_result(backend: str, prompt: str | None) -> str:
    if backend == "opencode":
        return prompt or ""
    if prompt:
        return json.dumps({"decision": "block", "reason": prompt})
    return "{}"


def _install_stop_hook(path: Path, handler: dict) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError) as exc:
            raise RuntimeError(f"cannot merge harness hook into {path}: {exc}") from exc
        if not isinstance(data, dict):
            raise RuntimeError(f"cannot merge harness hook into {path}: root must be an object")
    else:
        data = {}
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise RuntimeError(f"cannot merge harness hook into {path}: hooks must be an object")
    stop = hooks.setdefault("Stop", [])
    if not isinstance(stop, list):
        raise RuntimeError(f"cannot merge harness hook into {path}: hooks.Stop must be a list")
    if any(
        isinstance(group, dict)
        and any(
            isinstance(item, dict) and item.get("command") == handler["command"]
            for item in group.get("hooks", [])
        )
        for group in stop
    ):
        return "already present"
    stop.append({"hooks": [handler]})
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return "installed"


def install(root: Path) -> list[str]:
    """Install project-local lifecycle adapters without replacing user config."""
    statuses = [
        f"Codex: {_install_stop_hook(root / '.codex' / 'hooks.json', _CODEX_HANDLER)}",
        f"Claude: {_install_stop_hook(root / '.claude' / 'settings.json', _CLAUDE_HANDLER)}",
    ]
    plugin = root / ".opencode" / "plugins" / "orchestra.js"
    plugin.parent.mkdir(parents=True, exist_ok=True)
    if not plugin.exists():
        plugin.write_text(_OPENCODE_PLUGIN, encoding="utf-8")
        status = "installed"
    elif plugin.read_text(encoding="utf-8") == _OPENCODE_PLUGIN:
        status = "already present"
    else:
        status = f"preserved conflicting {plugin}"
    statuses.append(f"OpenCode: {status}")
    return statuses
